### PR TITLE
Setup refactor

### PR DESCRIPTION
**Pull request by nixjdm**
This PR is some more refactoring to make this a Python package that you can install to attain a CLI. The CLI is pretty basic, and replaces the shell scripts that were previously called directly. The top level `vagrant-boxes` dir was renamed to use an underscore, to make this a python package. Subdirs still use dashes at this time.

The contents of the old shell scripts are basically just copied into cli.py as strings that are ran, which is pretty hacky, but it's a start to cleaning things up a bit.

Example usage:
```
vagrant-boxes setup
vagrant-boxes build-json
vagrant-boxes build-full-boxes
```

This PR also contains some simple fixes for broken paths in templates.

### CODE REVIEW

**Comment by nixjdm** [comment]
Thanks for looking @alan-cugler 

1. I wasn't aware of this. I found #33 just now. I assume this is in reference to that. @verhulstm, why did you want all paths to be dashes? Is there a technical concern?

2. Fixed

3. I'm thinking I don't want to make it hidden. This is not a non-techie friendly repo in the first place, and I feel like a hidden dir would just be an annoyance to the techie. Maybe we don't need it all, but that's a different question, and I think out of the scope of this PR.

4. Fixed

**Comment by verhulstm** [comment]
@nixjdm  Q) "why did you want all paths to be dashes? " 

A ) no technical reason. Back in the day it was a mixture and i did not like the inconstancy. I a picked dashes.

**Comment by nixjdm** [comment]
Got it. Well the top level dir needs to not be dashes to be a valid Python package. So I can make them all underscores I guess.

**Comment by nixjdm** [comment]
On second though, there are a *ton* of dashes that would need fixed. It's not worth it. I'll gladly bear the inconsistency of the top-level dir instead of managing to change all of these dashes. It would be a lot of work, if done right the first time, and the risk of breaking something is super high. It probably shouldn't even be done outside of this PR, at least not with the current code base.

Barring changes after a bit more testing, I'll pull this.

**Pull request merged**
